[tool.poetry]
name = "aoc_day3"
version = "0.1.0"
description = ""
authors = ["BramReinders <bramreinders97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.5"
numpy = "^1.26.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
